### PR TITLE
Overhaul approach for dissolve module

### LINKED ISSUE #742: @turf/dissolve doesn't completely dissolve all geometries
Notice in the example below the two strangling polygons, whenever a geometry is completely within the dissolved outer ring some geometries seem to be excluded.

@rowanwins With many recent changes, we might want to revisit the source code for [`@turf/dissolve`](https://github.com/Turfjs/turf/blob/master/packages/turf-dissolve/index.js).

**Buffered points**
https://gist.github.com/490c0e00536ecc3ef1c98b74c40d2c29

image

**Dissolved points**
https://gist.github.com/7ad5ef7316f2a0a4a2578e9696902886
image

### LINKED ISSUE #1208: Dissolve fails with some polygons
I have a polygons that cause an error when using `dissolve`.

For instance : http://bl.ocks.org/d/25604e12a46464195ac7708fd879b4fe
The stacktrace:
```
Error: features must be of the same type
    at booleanOverlap (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:18806:32)
    at C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:43566:18
    at Array.forEach (native)
    at Object.dissolve$1 [as dissolve] (C:\Users\gdrouet\Documents\nomotech\node_modules\@turf\turf\turf.js:43542:42)
    at featureCollections.features.forEach.e (C:\Users\gdrouet\Documents\nomotech\index.js:20:40)
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\gdrouet\Documents\nomotech\index.js:9:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```
All features are polygons.

### LINKED ISSUE #1237: Dissolve failing
The dissolve function is failing on certain polygons.
Simply run this in the Javascript console and you'll see what I mean.

var aSmallfeatureCollection = JSON.parse('{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"combine":"yes"},"geometry":{"coordinates":[[[13491093.994242366,1545200.1726017569],[13491093.97839715,1545179.455050879],[13491073.391762003,1545179.47098838],[13491052.805126857,1545179.4869100656],[13491032.218490599,1545179.502815821],[13491011.631854339,1545179.5187056481],[13490991.045218082,1545179.5345795436],[13490970.458581822,1545179.5504376267],[13490949.871945562,1545179.5662798923],[13490929.285308192,1545179.5821061141],[13490908.698671931,1545179.5979165214],[13490888.112034561,1545179.6137111145],[13490888.127720587,1545200.331264407],[13490867.541067634,1545200.3470431964],[13490867.525396075,1545179.6294896617],[13490846.938758703,1545179.645252394],[13490826.352120219,1545179.6609993114],[13490805.765481733,1545179.6767301848],[13490785.178843247,1545179.6924452425],[13490764.592204759,1545179.7081444862],[13490744.005566277,1545179.723827685],[13490723.418926677,1545179.7394950679],[13490702.832287077,1545179.7551465223],[13490682.24564748,1545179.7707821608],[13490661.65900788,1545179.7864018702],[13490641.07236717,1545179.8020056488],[13490620.485726459,1545179.8175936136],[13490599.899085747,1545179.8331656493],[13490599.914552478,1545200.5507222048],[13490620.501208775,1545200.5351499298],[13490641.087865071,1545200.5195618377],[13490661.674520252,1545200.503957703],[13490661.69003374,1545221.2215292982],[13490682.27670562,1545221.2059091057],[13490702.8633775,1545221.1902730996],[13490723.450048266,1545221.174621162],[13490723.434486916,1545200.4570502914],[13490744.021142097,1545200.4413826673],[13490744.036719037,1545221.1589532965],[13490764.623389801,1545221.1432695005],[13490785.21005946,1545221.1275698894],[13490785.19445135,1545200.409999743],[13490805.781105421,1545200.394284443],[13490826.367759492,1545200.3785533283],[13490826.383399881,1545221.0961229934],[13490846.970069537,1545221.080375707],[13490867.55673919,1545221.0646124925],[13490888.143407732,1545221.0488333465],[13490888.159095988,1545241.7664180503],[13490888.174783131,1545262.4840184015],[13490908.761483954,1545262.4682229587],[13490929.348183667,1545262.4524115855],[13490949.93488449,1545262.4365843988],[13490970.521584202,1545262.4207412808],[13490991.108283913,1545262.4048822336],[13491011.69498251,1545262.3890073707],[13491032.28168222,1545262.373116464],[13491052.868380819,1545262.3572098569],[13491052.884194866,1545283.0748240384],[13491052.900010025,1545303.792453871],[13491052.915824072,1545324.5100994655],[13491073.502570538,1545324.49417609],[13491073.486739794,1545303.776530736],[13491094.07346956,1545303.7605917852],[13491094.057623232,1545283.0429624373],[13491094.041778015,1545262.3253487379],[13491094.025932798,1545241.6077506857],[13491094.010087583,1545220.8901683975],[13491093.994242366,1545200.1726017569]]],"type":"Polygon"}},{"type":"Feature","properties":{"combine":"yes"},"geometry":{"coordinates":[[[13490599.945484824,1545241.9858823756],[13490599.930018093,1545221.2682944096],[13490579.343346212,1545221.2838511118],[13490558.756673219,1545221.2993917689],[13490558.772107664,1545242.0169802185],[13490558.787543228,1545262.7345843152],[13490558.802977672,1545283.4522040612],[13490558.818413235,1545304.1698395703],[13490538.231677901,1545304.1853653782],[13490538.247096764,1545324.9030167768],[13490517.660344733,1545324.918526895],[13490517.675749125,1545345.6361941847],[13490497.08898151,1545345.651688615],[13490497.104370315,1545366.3693719108],[13490517.691153517,1545366.3538772396],[13490538.27793783,1545366.3383666375],[13490538.262517853,1545345.6206838253],[13490558.849285468,1545345.6051576505],[13490558.864721028,1545366.3228402217],[13490579.45150423,1545366.307297876],[13490600.038287431,1545366.2917397148],[13490620.62507063,1545366.2761656237],[13490620.609586088,1545345.5584836612],[13490600.022819586,1545345.5740576251],[13490600.007351745,1545324.856391185],[13490599.991885016,1545304.1387403957],[13490599.976418285,1545283.4211053688],[13490620.563136918,1545283.4055322434],[13490620.547654605,1545262.687913105],[13490620.532172289,1545241.9703097313],[13490599.945484824,1545241.9858823756]]],"type":"Polygon"}},{"type":"Feature","properties":{"combine":"yes"},"geometry":{"coordinates":[[[13491032.344877183,1545345.243668283],[13491052.931639232,1545345.2277607103],[13491052.915824072,1545324.5100994655],[13491032.329077607,1545324.5260067966],[13491032.344877183,1545345.243668283]]],"type":"Polygon"}}]}');
var flattened = turf.flatten(aSmallfeatureCollection);
console.log(flattened);
var dissolved = turf.dissolve(flattened);
console.log(dissolved);
// Uncaught Error: features must be of the same type,... even though they are all Polygons

### LINKED ISSUE #1806: Clarify 'propertyName' behaviour in dissolve
Currently `.dissolve()` supports a `property` option which is a pretty limited way of saying "apply the dissolve to these polygons, but not those ones".

A more flexible approach would be a filter function:

```js
var dissolved = turf.dissolve(features, { filter: f => f.properties.id === 47 } );
```

This way you're less likely to have to pre-massage the polygons to get the dissolve you want.

### LINKED ISSUE #1912: Dissolve@v7 returns a Feature, not a FeatureCollection
I'm using the v7 turf.dissolve to avoid the large jsts dependency. The documentation says that it returns a FeatureCollection, but it actually returns a MultiPolygon Feature, at least for me. Otherwise it works fine on any shapefile I give it. 

Input file: https://gist.github.com/lucaluca/001b0c034040169fd3bba9c33f3111cd
Output file: https://gist.github.com/lucaluca/84a448bf6d8cb2a35738ffa5019888c1

My code converts MultiPolygons in the input file into Polygons and then runs turf.dissolve:

```javascript
let newFeatures = []
shape.features.forEach(feature => {
  if (feature.geometry.type === 'MultiPolygon') {
    feature.geometry.coordinates.forEach(coordinates => {
      newFeatures.push({
        type: 'Feature',
        properties: feature.properties,
        id: feature.id,
        geometry: {
          type: 'Polygon',
          coordinates,
        },
      })
    })
  } else {
    newFeatures.push(feature)
  }
})
shape.features = newFeatures
shape = turf.dissolve(shape)
```

### LINKED ISSUE #2027: Dissolve does not keep property value
Hi.

I have tried to use dissolve in turf v7.0.0. Geometrically, everything works great, but dissolved polygons don't keep property.

For example:

```
var features = turf.featureCollection([
  turf.polygon([[[0, 0], [0, 1], [1, 1], [1, 0], [0, 0]]], {combine: 'yes'}),
  turf.polygon([[[0, -1], [0, 0], [1, 0], [1, -1], [0,-1]]], {combine: 'yes'}),
  turf.polygon([[[1,-1],[1, 0], [2, 0], [2, -1], [1, -1]]], {combine: 'no'}),
]);

var dissolved = turf.dissolve(features, {propertyName: 'combine'});
```
Feature collection is returned:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      ...,
      "properties": {},      >> Empty: I would expect property: combine: "yes"
      ...
    },
    {
      ...,
      "properties": {},      >> Empty: I would expect property: combine: "no"
      ...
    }
  ]
}
```
Thanks for your support!

### LINKED ISSUE #2074: dissolve() missing some overlapping polygon sections
I'm dissolving some circles created around train stations. Dissolve is mostly working but missing some overlaps

Here's a repro:

https://runkit.com/60222c3eed4360001bf54c3d/607d08c436949b0013662868

v6.3.0 

Screenshot 2021-04-19 at 2 29 58 PM

I haven't explored deeply, but I do notice that removing some of the polygons makes others behave better. That is, if there is a faulty non-dissolving overlap between circles C and D if there are A,B,C,D,E, then if we take away A, B and E, the fault may go away.

### PR DESCRIPTION
**Pull request by rowanwins**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occurred.
- [x] Run `npm run lint` to ensure code style at the turf module level.

This PR completely rewrites the dissolve module, the logic is now a lot simpler, and performance is improved.

Resolves #1806
Resolves #1912 
Resolves #1237
Resolves #1208
Resolves #742 
Resolves #2027
Resolves #2074

### CODE REVIEW

File: packages/turf-dissolve/index.js [hunk 1]
```diff
@@ -29,118 +24,49 @@ import { closestGreaterNumber } from "./lib/get-closest";
  * //addToMap
  * var addToMap = [features, dissolved]
  */
-function dissolve(featureCollection, options) {
+function dissolve(fc, options) {
   // Optional parameters
   options = options || {};
   if (!isObject(options)) throw new Error("options is invalid");
-  var propertyName = options.propertyName;
+  const propertyName = options.propertyName;
```
Comment (mfedderly) [inline packages/turf-dissolve/index.js:31]: Build is failing because `const` isn't es6 and we aren't doing any transpiling in non-ts modules as part of the build.

File: packages/turf-dissolve/index.js [hunk 2]
```diff
@@ -29,118 +24,49 @@ import { closestGreaterNumber } from "./lib/get-closest";
...
-      polygon = features[i];
-
-      var matchFeaturePosition =
-        potentialMatchingFeature.properties.origIndexPosition;
-
+  const outFeatures = [];
+  if (!options.propertyName) {
+    return featureCollection([
+      multiPolygon(
+        polygonClipping.union(...fc.features.map((f) => f.geometry.coordinates))
```
Comment (mfedderly) [inline packages/turf-dissolve/index.js:41]: Arrow functions also will probably fail the build

**Review by mfedderly — APPROVED** [review]
Code looks good, just build nits. Exciting to resolve so many tickets with a single PR.
Can you also run `yarn install` and check in the updated yarn.lock? I'm not sure why the build system isn't throwing an error there.

File: packages/turf-dissolve/index.js (hunk 2 above)
Comment (rowanwins) [reply packages/turf-dissolve/index.js]: The spread operator is also failing the es5 check, but that's the way polygonClipping accepts multiple polygons, need to think there if there a good way around that :(

Comment (mfedderly) [reply packages/turf-dissolve/index.js]: polygonClipping.union.apply or .call I can't remember which offhand. On mobile atm.

Comment (rowanwins) [reply packages/turf-dissolve/index.js]: Have replaced with `.apply()`

File: packages/turf-dissolve/index.js [hunk 3]
```diff
@@ -29,118 +24,54 @@ import { closestGreaterNumber } from "./lib/get-closest";
...
-    tree.search(polygon).features.forEach(function (potentialMatchingFeature) {
-      polygon = features[i];
-
-      var matchFeaturePosition =
-        potentialMatchingFeature.properties.origIndexPosition;
-
+  var outFeatures = [];
+  if (!options.propertyName) {
+    return featureCollection([
+      multiPolygon(
```
Comment (mfedderly) [inline packages/turf-dissolve/index.js:40]: MultiPolygon disagrees with the @returns in the jsdoc above and the typescript types that specify polygon.

File: packages/turf-dissolve/index.js [hunk 4]
```diff
@@ -29,118 +24,54 @@ import { closestGreaterNumber } from "./lib/get-closest";
...
     });
-
-    if (featureChanged) {
-      if (!polygon) continue;
-      polygon.properties.origIndexPosition = i;
-      tree.insert(polygon);
-      i--;
+    var vals = Object.keys(uniquePropertyVals);
+    for (var i = 0; i < vals.length; i++) {
+      var mp = multiPolygon(
```
Comment (mfedderly) [inline packages/turf-dissolve/index.js:61]: Another incidental change to MultiPolygon's here.

**Review by mfedderly — CHANGES_REQUESTED** [review]

File: packages/turf-dissolve/index.js (hunk 4 above)
Comment (rowanwins) [reply packages/turf-dissolve/index.js:61]: So `MultiPolygon` is what the polygonClipping library returns that we're using for this operation, we could turf.flatten to convert things into `polygon` if you thought that was helpful/necessary to prevent breaking backward compatibility.

File: packages/turf-dissolve/index.js (hunk 3 above)
Comment (rowanwins) [reply packages/turf-dissolve/index.js:40]: See comments below about what we want to return

File: packages/turf-dissolve/index.js (hunk 4 above)
Comment (mfedderly) [reply packages/turf-dissolve/index.js:61]: I think its probably worth the hassle to not break the API. If you want to file a ticket to do an API break for v7 that seems fine though.

Comment (rowanwins) [reply packages/turf-dissolve/index.js:62]: This should now be resolved by passing things through `flatten`

**Comment by JamesLMilner** [comment]
Would this also fix https://github.com/Turfjs/turf/issues/2074 ?

**Comment by rowanwins** [comment]
Yep it does @JamesLMilner

**Review by mfedderly — APPROVED** [review]
🥳
